---
# Commands to start on workspace startup
tasks:
  - init: yarn install
    command: yarn build
vscode:
  extensions:
    # TODO Once astro is on [vsx](https://open-vsx.org/), we should be able to specify it as an extension as well!
    # https://www.gitpod.io/docs/vscode-extensions
    - https://marketplace.visualstudio.com/_apis/public/gallery/publishers/astro-build/vsextensions/astro-vscode/0.7.13/vspackage
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
