[build]
publish = "public/"
command = "hugo --gc"

[[plugins]]
package = "netlify-plugin-cache-yarn2"

[[plugins]]
package = "netlify-plugin-debug-cache"

[dev]
command = "yarn start --site 'http://localhost:8888'"
framework = "#custom"
port = 8888
targetPort = 3000

[context.branch-deploy]
command = "yarn build --site $DEPLOY_PRIME_URL"

[context.deploy-preview]
command = "yarn build --site $DEPLOY_PRIME_URL"
