---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/episodes
  label: Episodes
  create: all
  match: "**/*.md"
upload_dir: public/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: yarn
  preview_docker_image: node:14
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn forestry:preview
